spring:
  application.name: recipe-sharing
  liquibase:
    enabled: true
    change-log: classpath:/liquibase/db.changelog-master.xml
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${spring.liquibase.user}
    password: ${spring.liquibase.password}
    url: ${spring.liquibase.url}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        hbm2ddl:
          auto: validate

jwt:
  header: Authorization
  secret: secretKey
  expiration: 720

security-configuration-properties:
  permit-all-urls:
    - /recipe-sharing/authentication/register
    - /recipe-sharing/authentication/login
    - /actuator/health
  swagger-urls:
    - /v3/api-docs/**
    - /swagger-ui/**